itanium-cxx-abi/cxx-abi

abi.html
As discussed in cxx-abi-dev thread entitled "Proposing an ABI restriction
on loads from an object's vtable pointer".
=> Introduce layout restrictions on virtual table pointers stored in objects and VTTs

abi.html
=> Specified that mangled name grammar productions that begin with the '$' character are reserved for private implementation use.

abi-mangling.html, abi.html
Formerly known as "decomposition declarations". As discussed on cxx-abi-dev@ in thread starting 2016-08-12.
=> Mangling for C++1z structured binding declarations

MAINTAINERS, README.md
It was mentioned in issue #11 that the canonical URL for the ABI specification is now the itanium-cxx-abi project instead of mentorembedded.  This change updates a few URLs to reference the new location.
=> Updated URLs in the README and MAINTAINERS files to reference the GitHub itanium-cxx-abi project instead of mentorembedded.

abi.html
OK, trying again on the right branch:
We've agreed on this several times over the years (in the thread "Transfer modes for parameters and return values"), but the document still hasn't been updated. In that thread Richard proposed the wording "[Pass an object of class type by value if] every copy constructor and move constructor is deleted or trivial and at least one of them is not deleted, and the destructor is trivial", but that requires reversing the sense of the paragraph; I believe that my wording here has the same effect.
=> Add move constructors to the invisible reference rule.

abi-layout.html, abi.html
This also corrects associated broken links.
=> Corrected some references to the <template-param> grammar production that were spelled as <template-parameter>.

abi.html
This mangling comes from Clang, historical warts and all; GCC does not currently support this attribute in C++.
=> Record the non-standard mangling of the GNU address_space attribute

abi.html
The discussions relating to incorporating exception-specifications into function types (starting with http://sourcerytools.com/pipermail/cxx-abi-dev/2016-October/002979.html) appear to never have been merged into the IA-64 specification.
I've gone through that thread and I *think* this pull request represents what was decided though I should mention a couple of items:
- I made an editorial change for "Dw <types>+ E" rather than "Dw <types>* E" because there should always be at least one type for this case.
- I didn't include __noreturn_mask because there seemed to be no consensus for it.
Let me know if I've misrepresented anything.
=> Incorporate exception-specification into mangling and type_info

abi.html
Update to more modern terminology where appropriate and drop anachronisms.
=> Include inline variables and variable templates in the list of contexts in which lambda closure types are mangled.

abi.html
=> Add layout rule for [[no_unique_address]] (C++20 P0840R2)

abi-mangling.html, abi.html
=> Add 'ss' as encoding for operator '<=>'.

abi.html
The section number is off by one.
I didn't see another PR for this, so if this is a duplicate please close.
=> Fix section number for `Transaction-Safe Function`

abi.html
Other `<special-name>` terms are written with a hyphen.
=> Fix underscore typo in special_name

abi.html
```
<name> ::= St <unqualified-name> # ::std::
```
is already covered by
```
<name> ::= <unscoped-name>
<unscoped-name> ::= St <unqualified-name>   # ::std::
```
=> Delete duplicate <name> mangling rule

abi-mangling.html, abi.html
This was proposed in cxx-abi-dev ([1](https://cxx-abi-dev.codesourcery.narkive.com/GGdYT1mo/coroutines-proposal-operator-co-await), [2](https://cxx-abi-dev.codesourcery.narkive.com/B4kGWkE0/operator-co-await)), has been used by Clang for years, and will likely be used by GCC ([relevant patch](https://gcc.gnu.org/ml/gcc-patches/2019-11/msg01611.html)).
Now coroutine has been merged into the draft standard, it seems to be time to add it to the ABI document.
=> Add 'aw' as encoding for operator 'co_await'

abi.html
Also clarify that deleted functions do get assigned vtable slots (even though they don't need them), and consolidate three different places and ways in which we enumerate the same set of rules for which functions get vtable slots and when a return type adjustment is necessary, so that we only need to say "non-consteval" in one place.
In passing, fix missing description of where and how to allocate vtable slots to implicit assignment operators (which might override a virtual assignment operator declared in a base class).
Fixes #82
=> Do not allocate vtable slots to `consteval` functions

abi-mangling.html, abi.html
I just noticed that some parts of the text refer to C++0x whereas others say C++11. The latter seems better.
=> Refer to C++11 rather than C++0x

abi.html
For example, in
```c++
struct B { template<class> void f(); };
struct A {
B b;
template<class T>
auto f() -> decltype(this->b.f<T>()) {}
};
template void A::f<int>();
```
`this->b` is mangled as `ptfpT1b`.
Tested GCC, Clang, and ICC: https://godbolt.org/z/Vdxn_5 .
=> Add 'fpT' as encoding for the 'this' pointer

abi.html
Allowing type parameters for vector extended types naturally allows
mangling of complex vendor extended types, like Clang's matrix type or
the various vector types.
This is in line with the grammarm for vendor extended qualifiers.
Fixes #100.
=> Extend grammar to allow parameterized vendor extension types.

abi.html
Builds on #96.
- Break it up into subsections for data and function member pointers
- Be much more precise
- Use portable concepts
- Include the ARM representation for virtual member functions pointers
- Add a future-platform recommendation about null data member pointers
=> [Editorial] Rewrite the section on member pointers

abi.html
Builds on #97.
- Reorganize it into separate subsections for function definitions, parameter conventions, and return-value conventions.
- Cross-reference the alignment requirement on non-static member functions, since it's easy to miss.
- Be explicit about the handling of this and VTT parameters.
The wording for empty parameters and return values leaves much to be desired, but I've left it as-is to make this a more purely editorial change.
=> [Editorial] Restructure the section on functions and calling conventions

abi.html
This could be used, for example, to mangle GCC's `__alignof__(type-or-expression)` extension.
Fixes #112
=> Add a new mangling for vendor extended expressions which may take expression or type arguments.

abi.html
C23 adds a new builtin datatype named `_BitInt` for a family of bit-precise integer types that can be either signed or unsigned. This adds a proper mangling for the datatype for implementations that provide this feature as an extension in C++ and for implementations that support overloading within C as an extension. This implements #128.
=> Add a mangling for the _BitInt datatype from C23.

abi.html
Extend grammar to cover additional contexts where this can be used.
Fixes #94.
=> Rename <data-member-prefix> to cover non-data member cases.

abi.html
This is a consequence of the existing wording, and makes sense for the same reason we don't want inline functions to be key functions in general, but is not universal implementation practice: GCC does not allow constexpr virtual functions to be key functions, but Clang 10 does.
=> Add a note that constexpr functions are never key functions.

cxx-abi-dev/index.html
Minor fix, so that the repo url points to the right location.
=> Fix link to repository

abi.html
The current mangling is missing entries for C23 _FloatNx and C++23 std::bfloat16_t; I propose adding another character after DF to indicate these variants.
There's also the related question about how we want to handle __float128 and __float80, and also __int64 and __int128, given the new model where the explicitly sized types are extended types rather than aliases for standard types of the same size.
My inclination is to change \_\_float128 to be another name for std::float128_t, and perhaps mangle std::float128_t as 'g' for compatibility with any existing code.  And change \_\_float80 to be another name for \_Float64x, mangled as DFx64_.  
Similarly, I'd treat __int64 as _BitInt(64), mangled as _DB64, and treat __int128 as _BitInt(128), still mangled as 'n'.
Thoughts?
=> Add mangling for _FloatNx and bfloat16_t

abi.html
Such resuing is allowed by [CWG43](https://wg21.link/cwg43), although Itanium ABI is still ignoring it.
=> Explain the "early version" that disallowed reusing tail padding of POD

abi.html
- Cover the impact of C++20 modules on v-table emission
- Clarify the wording in several places
- Weaken some constraints that should be unnecessary
- Note some platform divergences from the ABI
Addresses #170.
=> Update the section on the vague linkage of v-tables and RTTI

abi.html
Unescaped angle bracket pairs are interpreted as an HTML tag.
=> Escape angle brackets

abi.html
This is referenced in a couple of places but never defined in the mangled name grammar.
=> Add missing grammar rule for `<float>`

abi.html
The document is weirdly indented by w3m's renderer. Fix that by explicitly closing all `<dd>` tags.
=> Add missing HTML </dd> tags

abi.html
Typo noticed will reading https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling.dependent.
Please apply when you can.
Thanks, Simon
=> Fix typo in abi.html: xpression => expression.
